openapi: 3.0.1
info:
  title: Open API integrations generator Plugin
  description: A plugin that generates a client in your language
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /clients/generate:
    post:
      requestBody:
        description: Generates a stub API client
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/generationRequest'
      responses:
        "200":
          description: OK
comonent:
  schemas:
    generationReqiest:
      type: object
      properties:
        language:
          type: string
      required:
        - language